// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AsdClient is the client API for Asd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsdClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type asdClient struct {
	cc grpc.ClientConnInterface
}

func NewAsdClient(cc grpc.ClientConnInterface) AsdClient {
	return &asdClient{cc}
}

func (c *asdClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sds.xcvxc.Asd/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsdServer is the server API for Asd service.
// All implementations must embed UnimplementedAsdServer
// for forward compatibility
type AsdServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAsdServer()
}

// UnimplementedAsdServer must be embedded to have forward compatible implementations.
type UnimplementedAsdServer struct {
}

func (UnimplementedAsdServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAsdServer) mustEmbedUnimplementedAsdServer() {}

// UnsafeAsdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsdServer will
// result in compilation errors.
type UnsafeAsdServer interface {
	mustEmbedUnimplementedAsdServer()
}

func RegisterAsdServer(s grpc.ServiceRegistrar, srv AsdServer) {
	s.RegisterService(&Asd_ServiceDesc, srv)
}

func _Asd_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sds.xcvxc.Asd/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Asd_ServiceDesc is the grpc.ServiceDesc for Asd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Asd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sds.xcvxc.Asd",
	HandlerType: (*AsdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Asd_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Asd.proto",
}
