// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: Ass.proto

package sd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssClient is the client API for Ass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type assClient struct {
	cc grpc.ClientConnInterface
}

func NewAssClient(cc grpc.ClientConnInterface) AssClient {
	return &assClient{cc}
}

func (c *assClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/ssd.sd.Ass/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssServer is the server API for Ass service.
// All implementations must embed UnimplementedAssServer
// for forward compatibility
type AssServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAssServer()
}

// UnimplementedAssServer must be embedded to have forward compatible implementations.
type UnimplementedAssServer struct {
}

func (UnimplementedAssServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAssServer) mustEmbedUnimplementedAssServer() {}

// UnsafeAssServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssServer will
// result in compilation errors.
type UnsafeAssServer interface {
	mustEmbedUnimplementedAssServer()
}

func RegisterAssServer(s grpc.ServiceRegistrar, srv AssServer) {
	s.RegisterService(&Ass_ServiceDesc, srv)
}

func _Ass_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssd.sd.Ass/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ass_ServiceDesc is the grpc.ServiceDesc for Ass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ssd.sd.Ass",
	HandlerType: (*AssServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ass_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ass.proto",
}
